version: "3.8"

services:
  db:
    image: mysql:8
    container_name: expense_tracker_db
    restart: always
    environment:
      MYSQL_DATABASE: expense_tracker
      MYSQL_ROOT_PASSWORD: siddu1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./expensetracker
    container_name: expense_tracker_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/expense_tracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: siddu1234

  frontend:
    build: ./expense-tracker-frontend
    container_name: expense_tracker_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  db_data:

networks:
  app-network:
